# Generated by Django 6.0 on 2025-12-22 18:44

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="Опис категорії"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Назва категорії", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Автор коментаря",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(help_text="Ваш коментар"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Оцініть цей рецепт (1-5 зірок)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="recipe",
            field=models.ForeignKey(
                help_text="Назва рецепту",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="cookbook.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                help_text="Автор рецепту",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                help_text="Категорія рецепту",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="cookbook.category",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                help_text="Час приготування в хвилинах",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(help_text="Короткий опис страви"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Додайте світлину страви",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                help_text="Список інгрідієнтів (кожен з нової стрічки"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(help_text="Покрокова інструкція приготування"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Кількість порцій",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Тег для рецепту",
                related_name="recipes",
                to="cookbook.tag",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(help_text="Назва рецепту", max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(help_text="Назва тегу", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(help_text="URL-friendly версія назви", unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, help_text="Про себе", max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Додайте світлину",
                max_length=255,
                null=True,
                verbose_name="profile image",
            ),
        ),
    ]
