# Generated by Django 6.0 on 2025-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0002_alter_category_description_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                help_text="Список інгредієнтів (кожен з нової стрічки)"
            ),
        ),
    ]
