# Generated by Django 6.0 on 2026-01-01 22:03

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0003_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="Category description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Comment author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(help_text="Enter your comment here"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rate this recipe (1-5 stars)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="recipe",
            field=models.ForeignKey(
                help_text="Recipe name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="cookbook.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                help_text="Recipe author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                help_text="Recipe category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="cookbook.category",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                help_text="Cooking time in minutes",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(help_text="Short description of the dish"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload a photo of your dish",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(help_text="List of ingredients (one per line)"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(help_text="Step-by-step cooking instructions"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of servings",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Recipe tags",
                related_name="recipes",
                to="cookbook.tag",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(help_text="Receipe title", max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(help_text="Tag name", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Tell us about yourself", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload your profile picture",
                max_length=255,
                null=True,
                verbose_name="profile image",
            ),
        ),
    ]
